language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.1
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - gemfiles/middleman_3.1.gemfile
  - gemfiles/middleman_3.2.gemfile
  - gemfiles/middleman_3.4.gemfile
  - gemfiles/middleman_3_stable.gemfile
  - gemfiles/middleman_4.0.gemfile
  - gemfiles/middleman_4.1.gemfile
  - gemfiles/middleman_master.gemfile
